environment:
  global:
    REPO_DIR: biopython
    PACKAGE_NAME: biopython
    BUILD_COMMIT: biopython-171
    WHEELHOUSE_UPLOADER_USERNAME: travis-worker
    WHEELHOUSE_UPLOADER_SECRET:
        secure:
            rGyl1dSDGB0VGdWO6GVnSRDfbsXxqENaRXRWFjRI91hOQVbgcmYphSQ+wNBzO1LB

  matrix:
    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      BUILD_DEPENDS: "numpy==1.8.0"
      TEST_DEPENDS: "numpy==1.8.0"
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      BUILD_DEPENDS: "numpy==1.8.0"
      TEST_DEPENDS: "numpy==1.8.0"
    - PYTHON: "C:\\Miniconda34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      BUILD_DEPENDS: "numpy==1.9.0"
      TEST_DEPENDS: "numpy==1.9.0"
    - PYTHON: "C:\\Miniconda34-x64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      BUILD_DEPENDS: "numpy==1.9.0"
      TEST_DEPENDS: "numpy==1.9.0"
    - PYTHON: "C:\\Miniconda35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      BUILD_DEPENDS: "numpy==1.10.1"
      TEST_DEPENDS: "numpy==1.10.1"
    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      BUILD_DEPENDS: "numpy==1.10.1"
      TEST_DEPENDS: "numpy==1.10.1"
    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      BUILD_DEPENDS: "numpy==1.12.0"
      TEST_DEPENDS: "numpy==1.12.0"
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      BUILD_DEPENDS: "numpy==1.12.0"
      TEST_DEPENDS: "numpy==1.12.0"


# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

matrix:
    fast_finish: false  # for testing

install:
    # Fetch submodules
    - git submodule update --init --recursive

    # Install miniconda
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PYTHON%\Library\bin;%PATH%
    - conda info

    # Update pip
    - python -m ensurepip
    - python -m pip install --upgrade pip

    # Fix MSVC builds for 64-bit Python. See:
    # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
    - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"

    # Check that we have the expected version and architecture for Python
    - python --version
    - python -c "import struct; print(struct.calcsize('P') * 8)"

build_script:
    # Install build requirements
    - conda install --yes %BUILD_DEPENDS%

    # build wheel:
    - cd %REPO_DIR%
    - git checkout %BUILD_COMMIT%
    - SET DISTUTILS_DEBUG=1
    - python setup.py bdist_wheel
    - ls dist/

test_script:
    # create test env
    - conda create --yes -n test_env python=%PYTHON_VERSION% %TEST_DEPENDS%
    - activate test_env

    # install from wheel
    - pip install --no-index --find-links dist/ %PACKAGE_NAME%

    # run test from installed wheel.
    - cd ..
    - "python -c \"import Bio; print('Biopython version ' + Bio.__version__)\""
    # This will confirm some of our C code compiled fine:
    - "python -c \"from Bio.Nexus import cnexus; from Bio import cpairwise2\""
    - "python -c \"from Bio import Cluster; print('Bio.Cluster version ' + Cluster.version())\""
    # Now let's run our full test suite...
    # We want to do this using the Biopython installed from the wheel,
    # so just want the Tests (and Doc) folders present here:
    - mv %REPO_DIR%\\Tests Tests
    - mv %REPO_DIR%\\Doc Doc
    - cd Tests
    # Disable doctest which breaks under 64-bit Python 2.7
    - "sed -i.tmp 's:\"Bio.Affy.CelFile\",:# Skip Bio.Affy.CelFile:g' run_tests.py"
    # Disable int vs long tutorial doctest which breaks under 32-bit Python 3.5
    - rm ..\\Doc\\Tutorial\\chapter_phenotype.tex
    # Disable two more platform specific failures
    - "sed -i.tmp 's#def test_WellRecord#def no_test_WellRecord#g' test_phenotype.py"
    - "sed -i.tmp 's#def test_phenotype_IO#def no_test_phenotype_IO#g' test_phenotype.py"
    - "python run_tests.py --offline"
    - cd ..

artifacts:
    - path: "%REPO_DIR%\\dist\\*"

on_success:
  # Report checksums
  # - md5sum %REPO_DIR%\\dist\\%PACKAGE_NAME%*
  # - sha256sum %REPO_DIR%\\dist\\%PACKAGE_NAME%*
  # Upload the generated wheel package to Rackspace
  # On Windows, Apache Libcloud cannot find a standard CA cert bundle so we
  # disable the ssl checks.
  - pip install wheelhouse-uploader
  - "python -m wheelhouse_uploader upload
    --no-ssl-check --local-folder=%REPO_DIR%\\dist --no-update-index wheels"
